# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: iptest_update

on:
  workflow_dispatch:

permissions:
  contents: write
  discussions: write

jobs:

  build:
    runs-on: ubuntu-24.04
    
    steps:
    - uses: actions/checkout@v4

    - name: build 
      run: tar --exclude='./iptest/*/*' -czf iptest.tar.gz ./iptest/*

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
          files: iptest.tar.gz
          tag_name:  v.iptest
          append_body: false
          generate_release_notes: true
